'use client';

import Script from 'next/script';
import { type RefObject, useCallback, useEffect, useRef, useState } from 'react';

const CALENDLY_EMBED_URL = 'https://calendly.com/divineacquisition/deployment-call?hide_event_type_details=1&hide_gdpr_banner=1';
const VSL_EMBED_URL =
  'https://player.vimeo.com/video/76979871?autoplay=0&muted=1&controls=1&title=0&byline=0&portrait=0&dnt=1';

type FaqItem = {
  question: string;
  answer: string;
};

type OutcomeCard = {
  metric: string;
  title: string;
  description: string;
};

type Capability = {
  headline: string;
  visual: string;
  copy: string;
};

type DeploymentStep = {
  title: string;
  description: string;
};

type IncludedItem = {
  title: string;
  description: string;
};

const outcomes: OutcomeCard[] = [
  {
    metric: '3x',
    title: 'Serve triple the clients',
    description:
      'Your current team handles 3x more accounts without a single hire. The system runs the operational layer. Your people do the thinking.',
  },
  {
    metric: '60-70%',
    title: 'Cut operational costs',
    description:
      'Avoid $120K-$180K in annual hiring by automating the roles you were about to post. Junior admin work disappears. Every person on your team does billable strategic work.',
  },
  {
    metric: '5 min',
    title: 'Reports that took 4 hours',
    description:
      'Weekly client reports, Monday morning briefs, health overviews, CSM priority lists — all generated by AI using your actual data. Your team reviews for 5 minutes instead of building for 4 hours.',
  },
];

const capabilities: Capability[] = [
  {
    headline: 'Every client monitored 24/7',
    visual:
      'Screenshot target: Airtable Client Roster with health scores in green/yellow/orange/red and trend arrows.',
    copy: 'Health scores calculated daily from interaction frequency, sentiment, deliverable status, billing health, and contract timeline. When a client starts slipping, the system catches it the same day — not three weeks later when they send the cancellation email.',
  },
  {
    headline: 'Check-ins that write themselves',
    visual:
      "Screenshot target: Slack message with AI-drafted check-in email that references client's name and active project.",
    copy: "The AI drafts personalized check-in messages using everything it knows about the client — their project, their last call, their preferences, their communication style. Not templates. Messages that reference real context. Your CSM reviews in 30 seconds and sends, or the system sends automatically.",
  },
  {
    headline: 'Reports built in seconds, not hours',
    visual:
      'Screenshot target: Monday weekly brief in Slack with client names, health scores, and recommended next actions.',
    copy: 'Weekly operational briefs land in Slack every Monday at 8am. Client performance reports auto-generate monthly. CSM priority lists arrive daily — ranked by urgency with exact actions. Every report uses real data, real client names, real numbers. No manual spreadsheet building.',
  },
  {
    headline: 'Retention that runs while you sleep',
    visual:
      'Screenshot target: GHL workflow view with sequence steps (email, wait, SMS, wait, escalation).',
    copy: "When a client's health drops, a multi-step retention sequence fires automatically. Check-in email within 4 hours. SMS follow-up if no reply in 3 days. Escalation to the owner if still silent. The system runs the sequence. Humans intervene only when the system says they're needed.",
  },
  {
    headline: 'Renewals that never get missed',
    visual:
      'Screenshot target: Airtable Renewals Coming view showing contracts and days-until-expiry calculations.',
    copy: 'Every contract is tracked. At 60 days out, the team gets alerted. At 30 days, the AI drafts a renewal touch email. At 15 days, the owner gets an urgent notification. No contract ever expires because nobody was watching the calendar.',
  },
  {
    headline: 'Your entire team knows what to do every morning',
    visual:
      "Screenshot target: Slack morning priority post with at-risk clients, follow-ups due, and renewals listed.",
    copy: 'Every CSM gets a daily priority list in Slack. Every morning. Ranked by urgency. At-risk clients at the top, healthy clients at the bottom. No guessing. No Monday morning scramble. Open Slack, read the list, start working.',
  },
];

const deploymentSteps: DeploymentStep[] = [
  {
    title: 'We map your operations',
    description:
      '30-minute call. I walk through your current process — tools, team, clients, gaps. You fill out a short questionnaire so I can prepare a custom assessment.',
  },
  {
    title: 'We deploy in 4-6 weeks',
    description:
      'Every automation built and configured for your agency. Client data imported. Health scoring calibrated. Workflows armed. Slack connected. AI agent trained on your business.',
  },
  {
    title: 'We train your team',
    description:
      '60-90 minute walkthrough. Every dashboard, every form, every Slack notification, every daily routine. Recorded for new hires.',
  },
  {
    title: 'We run it monthly',
    description:
      'System monitoring. Workflow optimization. Weekly briefs generated and delivered. Monthly strategy call. Network intelligence updates. Cancel anytime — system goes offline.',
  },
];

const includedItems: IncludedItem[] = [
  {
    title: 'Client data command center',
    description:
      '13 tables centralizing every client, contact, project, invoice, and interaction in one workspace',
  },
  {
    title: 'Health scoring engine',
    description: 'Daily automated scoring across 6 factors with trend tracking and risk detection',
  },
  {
    title: '8 automated fulfillment funnels',
    description:
      'Onboarding, check-in cadence, retention save, renewal sequence, reporting, escalation routing, content pipeline, billing follow-up',
  },
  {
    title: 'AI operations agent',
    description:
      'Weekly briefs, daily CSM priorities, call prep, personalized message drafts, health analysis',
  },
  {
    title: '15 message templates',
    description:
      "Check-ins, retention, renewals, onboarding, escalation — all customized to your agency's voice",
  },
  {
    title: 'Slack or Discord integration',
    description:
      'Morning priorities, health alerts, escalation notifications, agent action log, weekly brief delivery',
  },
  {
    title: 'Team dashboard',
    description: 'Health overview, CSM workload, capacity planning, network benchmarks',
  },
  {
    title: 'Client reporting automation',
    description: 'Weekly and monthly reports generated from your actual data, delivered to Slack or email',
  },
  {
    title: 'Full team training',
    description: 'Recorded 60-90 minute walkthrough of every system, form, and daily routine',
  },
  {
    title: 'DA network intelligence',
    description:
      'Anonymous benchmarks from all agencies in our network feeding better predictions and recommendations into your system',
  },
];

const faqs: FaqItem[] = [
  {
    question: 'What tools do you use?',
    answer:
      'We deploy across Airtable, GHL, Google Sheets, Claude AI, Resend, and Telnyx — integrated with your existing Slack or Discord. We connect to whatever CRM, project management tool, and billing system you already use. You do not switch tools. We layer intelligence on top of what you have.',
  },
  {
    question: 'How long does deployment take?',
    answer:
      '4 weeks for Foundation ($8K). 6 weeks for Scale ($12K). Your system is live and your team is trained by the end of deployment.',
  },
  {
    question: 'What happens if I cancel the retainer?',
    answer:
      'The automated workflows, AI agent, reports, and network intelligence go offline. Your data in Airtable stays yours permanently. We do not hold anything hostage — but the system requires ongoing operation to function.',
  },
  {
    question: 'Do you work with my type of agency?',
    answer:
      'We work with marketing agencies (SEO, paid media, content, social, web dev, branding) and recruiting/staffing agencies. If you manage 10+ active client accounts with a team of 5-30 people, the system fits.',
  },
  {
    question: 'What if I only have 10-15 clients?',
    answer:
      'That is the starting sweet spot. The system scales with you. Most agencies start at 10-20 clients and grow to 40-50 within 6-12 months because the operational ceiling is removed.',
  },
  {
    question: 'How is this different from just using GHL or Monday or HubSpot?',
    answer:
      'Those are individual tools. You still need someone to configure them, connect them, monitor them, and act on the data. We deploy a complete operations layer — the tools are wired together with AI intelligence on top. The system does not just store data. It watches every client, catches problems, writes messages, generates reports, and tells your team exactly what to do every morning.',
  },
  {
    question: 'What do I need to provide?',
    answer:
      'Your client list (CSV or manual), your team info, your communication channel access (Slack webhook, email domain), and 60 minutes for the onboarding call. We handle everything else.',
  },
];

type FbqEventType = 'track' | 'trackCustom';

interface VimeoPlayerInstance {
  on: (eventName: string, callback: (payload: { percent: number }) => void) => void;
  destroy: () => void;
}

declare global {
  interface Window {
    fbq?: (eventType: FbqEventType, eventName: string, params?: Record<string, unknown>) => void;
    Vimeo?: {
      Player: new (target: HTMLIFrameElement) => VimeoPlayerInstance;
    };
  }
}

function fireFacebookEvent(
  eventType: FbqEventType,
  eventName: string,
  params?: Record<string, unknown>,
) {
  if (typeof window === 'undefined') {
    return;
  }

  if (typeof window.fbq === 'function') {
    window.fbq(eventType, eventName, params);
  }
}

function formatStepNumber(step: number) {
  return step.toString().padStart(2, '0');
}

function VslEmbed({
  iframeRef,
  caption,
}: {
  iframeRef?: RefObject<HTMLIFrameElement | null>;
  caption: string;
}) {
  return (
    <div className="space-y-3">
      <div className="overflow-hidden rounded-2xl border border-white/10 bg-black">
        <div className="aspect-video w-full">
          <iframe
            ref={iframeRef}
            src={VSL_EMBED_URL}
            title="Divine Acquisition VSL"
            className="h-full w-full"
            allow="autoplay; fullscreen; picture-in-picture; encrypted-media"
            loading="lazy"
          />
        </div>
      </div>
      <p className="text-center text-sm text-neutral-400">{caption}</p>
    </div>
  );
}

function ScreenPlaceholder({ text }: { text: string }) {
  return (
    <div className="rounded-2xl border border-neutral-200 bg-white p-5">
      <div className="mb-4 flex items-center gap-2">
        <span className="h-2.5 w-2.5 rounded-full bg-red-400" />
        <span className="h-2.5 w-2.5 rounded-full bg-amber-400" />
        <span className="h-2.5 w-2.5 rounded-full bg-emerald-400" />
        <span className="ml-2 text-xs font-medium text-neutral-500">System Screenshot</span>
      </div>
      <div className="rounded-xl border border-neutral-200 bg-neutral-50 p-4">
        <p className="text-sm leading-relaxed text-neutral-600">{text}</p>
      </div>
    </div>
  );
}

export default function DemoPage() {
  const [activeFaqIndex, setActiveFaqIndex] = useState<number | null>(0);
  const [openIncludedIndex, setOpenIncludedIndex] = useState<number | null>(0);
  const trackedMilestonesRef = useRef<Set<number>>(new Set());
  const playersRef = useRef<VimeoPlayerInstance[]>([]);
  const heroVideoRef = useRef<HTMLIFrameElement | null>(null);
  const midPageVideoRef = useRef<HTMLIFrameElement | null>(null);

  const trackVslMilestones = useCallback((percent: number) => {
    const percentValue = percent * 100;
    const milestones = [25, 50, 75, 100];

    for (const milestone of milestones) {
      const reached = milestone === 100 ? percentValue >= 99.5 : percentValue >= milestone;
      if (reached && !trackedMilestonesRef.current.has(milestone)) {
        trackedMilestonesRef.current.add(milestone);
        fireFacebookEvent('trackCustom', `VSL_${milestone}_Watched`, { milestone });
      }
    }
  }, []);

  const initializeVimeoPlayers = useCallback(() => {
    if (typeof window === 'undefined' || !window.Vimeo?.Player) {
      return;
    }

    const refs = [heroVideoRef.current, midPageVideoRef.current].filter(
      (value): value is HTMLIFrameElement => Boolean(value),
    );

    if (refs.length === 0) {
      return;
    }

    playersRef.current.forEach((player) => player.destroy());
    playersRef.current = refs.map((iframe) => {
      const player = new window.Vimeo!.Player(iframe);
      player.on('timeupdate', (payload) => trackVslMilestones(payload.percent));
      return player;
    });
  }, [trackVslMilestones]);

  useEffect(() => {
    fireFacebookEvent('track', 'PageView');

    const handleCalendlyEvent = (event: MessageEvent) => {
      if (
        typeof event.data === 'object' &&
        event.data !== null &&
        'event' in event.data &&
        event.data.event === 'calendly.event_scheduled'
      ) {
        fireFacebookEvent('track', 'Lead');
      }
    };

    window.addEventListener('message', handleCalendlyEvent);

    if (window.Vimeo?.Player) {
      initializeVimeoPlayers();
    }

    return () => {
      window.removeEventListener('message', handleCalendlyEvent);
      playersRef.current.forEach((player) => player.destroy());
      playersRef.current = [];
    };
  }, [initializeVimeoPlayers]);

  const handleCtaClick = () => {
    fireFacebookEvent('track', 'InitiateCheckout');
  };

  return (
    <main className="bg-[#09090b] text-white">
      <Script
        src="https://player.vimeo.com/api/player.js"
        strategy="afterInteractive"
        onLoad={initializeVimeoPlayers}
      />

      <section className="px-6 py-16 md:py-24">
        <div className="mx-auto max-w-4xl text-center">
          <h1 className="text-4xl font-semibold leading-tight tracking-tight sm:text-5xl md:text-6xl">
            Your agency is losing clients you could save.
          </h1>
          <p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-neutral-300 md:text-xl">
            Watch how one system automates 80% of your operational overhead so your team serves 3x
            more clients without hiring.
          </p>
          <div className="mt-10">
            <VslEmbed
              iframeRef={heroVideoRef}
              caption="12 minutes. No pitch. Just the system in action."
            />
          </div>
        </div>
      </section>

      <section className="border-y border-white/10 bg-black px-4 py-3">
        <p className="text-center text-sm text-neutral-200">
          Built on infrastructure managing 50+ client relationships across multiple industries.
        </p>
      </section>

      <section className="bg-white px-6 py-16 text-neutral-900 md:py-20">
        <div className="mx-auto max-w-6xl">
          <div className="grid grid-cols-1 gap-5 md:grid-cols-3">
            {outcomes.map((card) => (
              <article key={card.title} className="rounded-2xl border border-neutral-200 p-6 md:p-7">
                <p className="text-4xl font-bold tracking-tight md:text-5xl">{card.metric}</p>
                <h2 className="mt-3 text-xl font-semibold">{card.title}</h2>
                <p className="mt-3 text-sm leading-relaxed text-neutral-700">{card.description}</p>
              </article>
            ))}
          </div>
          <div className="mt-10 text-center">
            <a
              href="#booking-widget"
              onClick={handleCtaClick}
              className="inline-flex items-center justify-center rounded-full bg-[#5500FF] px-8 py-3 text-sm font-semibold text-white transition hover:bg-[#6d23ff]"
            >
              Book the call
            </a>
          </div>
        </div>
      </section>

      <section className="bg-neutral-100 px-6 py-16 text-neutral-900 md:py-20">
        <div className="mx-auto max-w-4xl rounded-2xl bg-neutral-100">
          <h2 className="text-3xl font-semibold tracking-tight md:text-4xl">
            Here&apos;s what&apos;s actually happening inside your agency right now.
          </h2>
          <div className="mt-8 space-y-5 text-base leading-relaxed text-neutral-700 md:text-lg">
            <p>
              Your CSMs manage 15-20 accounts each. They spend 30% of their week writing check-in
              emails. 25% building reports. 15% chasing team members for project updates. 10% on
              admin — logging calls, updating spreadsheets, filing things in the right folder.
            </p>
            <p>
              That leaves 20% for the work that actually keeps clients — strategy, creative
              thinking, relationship building.
            </p>
            <p>
              Your best people are buried in operational overhead. They&apos;re not bad at their jobs.
              The job is structured wrong.
            </p>
            <p>
              Meanwhile, clients go quiet and nobody notices. Deliverables ship late and the CSM
              finds out from the client, not the system. Contracts expire without anyone starting
              the renewal conversation. A client you&apos;ve had for two years leaves because they felt
              ignored — not because the work was bad.
            </p>
            <p>
              Every one of those lost clients was preventable. Not with more effort. With better
              infrastructure.
            </p>
          </div>
        </div>
      </section>

      <section className="bg-black px-6 py-16 md:py-20">
        <div className="mx-auto max-w-4xl text-center">
          <h2 className="text-3xl font-semibold tracking-tight md:text-4xl">
            See the entire system in 12 minutes.
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-neutral-300">
            Screen recording of a live agency operations dashboard. Not slides. Not promises. The
            actual system running.
          </p>
          <div className="mt-8">
            <VslEmbed
              iframeRef={midPageVideoRef}
              caption="This is what Monday morning looks like when your ops are automated."
            />
          </div>
        </div>
      </section>

      <section className="bg-white px-6 py-16 text-neutral-900 md:py-20">
        <div className="mx-auto max-w-6xl">
          <h2 className="text-center text-3xl font-semibold tracking-tight md:text-4xl">
            What the system does
          </h2>
          <div className="mt-12 space-y-8">
            {capabilities.map((item, index) => (
              <article
                key={item.headline}
                className="grid grid-cols-1 items-center gap-6 rounded-2xl border border-neutral-200 p-5 md:grid-cols-2 md:p-7"
              >
                <div className={index % 2 === 1 ? 'md:order-2' : ''}>
                  <h3 className="text-2xl font-semibold">{item.headline}</h3>
                  <p className="mt-3 text-neutral-700">{item.copy}</p>
                </div>
                <div className={index % 2 === 1 ? 'md:order-1' : ''}>
                  <ScreenPlaceholder text={item.visual} />
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-neutral-50 px-6 py-16 text-neutral-900 md:py-20">
        <div className="mx-auto max-w-6xl">
          <h2 className="text-center text-3xl font-semibold tracking-tight md:text-4xl">
            How it works
          </h2>
          <div className="mt-10 grid grid-cols-1 gap-5 md:grid-cols-4">
            {deploymentSteps.map((step, index) => (
              <article key={step.title} className="rounded-2xl border border-neutral-200 bg-white p-6">
                <div className="mb-4 flex items-center gap-3">
                  <span className="inline-flex h-9 w-9 items-center justify-center rounded-full bg-[#5500FF] text-sm font-semibold text-white">
                    {formatStepNumber(index + 1)}
                  </span>
                  <h3 className="text-lg font-semibold">{step.title}</h3>
                </div>
                <p className="text-sm leading-relaxed text-neutral-700">{step.description}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-white px-6 py-16 text-neutral-900 md:py-20">
        <div className="mx-auto max-w-6xl">
          <h2 className="text-center text-3xl font-semibold tracking-tight md:text-4xl">
            Price anchor
          </h2>
          <div className="mt-10 grid grid-cols-1 gap-5 md:grid-cols-2">
            <article className="rounded-2xl border border-red-200 bg-red-50 p-6">
              <h3 className="text-2xl font-semibold">Build it yourself</h3>
              <ul className="mt-5 space-y-2 text-neutral-700">
                <li>Data analyst: $55,000-$75,000/year</li>
                <li>Retention specialist: $50,000-$65,000/year</li>
                <li>RevOps / automation person: $60,000-$80,000/year</li>
              </ul>
              <p className="mt-5 text-lg font-semibold">Total: $165,000-$220,000/year</p>
              <p className="mt-2 text-sm text-neutral-600">
                Plus 6 months to build, train, and iterate.
              </p>
            </article>
            <article className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6">
              <h3 className="text-2xl font-semibold">Deploy with Divine Acquisition</h3>
              <ul className="mt-5 space-y-2 text-neutral-700">
                <li>Setup: $8,000-$12,000 (one time)</li>
                <li>Monthly: $997-$1,497/month</li>
              </ul>
              <p className="mt-5 text-lg font-semibold">Year 1 total: $20,000-$30,000</p>
              <p className="mt-2 text-sm text-neutral-600">
                Live in 4-6 weeks. No hiring. No management overhead.
              </p>
            </article>
          </div>
          <p className="mt-8 text-center text-lg font-semibold">
            One saved client pays for the entire first year.
          </p>
          <div className="mt-8 text-center">
            <a
              href="#booking-widget"
              onClick={handleCtaClick}
              className="inline-flex items-center justify-center rounded-full bg-[#5500FF] px-8 py-3 text-sm font-semibold text-white transition hover:bg-[#6d23ff]"
            >
              Book the call
            </a>
          </div>
        </div>
      </section>

      <section className="bg-neutral-50 px-6 py-16 text-neutral-900 md:py-20">
        <div className="mx-auto max-w-5xl">
          <h2 className="text-center text-3xl font-semibold tracking-tight md:text-4xl">
            Everything deployed in your agency
          </h2>
          <div className="mt-10 space-y-3">
            {includedItems.map((item, index) => {
              const isOpen = openIncludedIndex === index;
              return (
                <article key={item.title} className="overflow-hidden rounded-xl border border-neutral-200 bg-white">
                  <button
                    className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left"
                    onClick={() => setOpenIncludedIndex(isOpen ? null : index)}
                  >
                    <div className="flex items-start gap-3">
                      <span className="mt-1 inline-flex h-2.5 w-2.5 rounded-full bg-[#5500FF]" />
                      <p className="font-semibold text-neutral-900">{item.title}</p>
                    </div>
                    <span className="text-xl text-neutral-500">{isOpen ? '−' : '+'}</span>
                  </button>
                  {isOpen ? (
                    <p className="px-5 pb-5 text-sm leading-relaxed text-neutral-700">{item.description}</p>
                  ) : null}
                </article>
              );
            })}
          </div>
        </div>
      </section>

      <section className="bg-[#0f0f13] px-6 py-16 md:py-20">
        <div className="mx-auto max-w-4xl rounded-2xl border border-white/10 bg-black p-8 md:p-10">
          <h2 className="text-3xl font-semibold tracking-tight md:text-4xl">
            Your system gets smarter every month.
          </h2>
          <p className="mt-5 leading-relaxed text-neutral-300">
            Every agency we deploy for contributes anonymized data to our network intelligence. We
            do not share your client names or data with anyone. But we track patterns across all
            agencies in the network.
          </p>
          <div className="my-8 text-center">
            <p className="text-6xl font-bold text-[#907DFF]">62%</p>
            <p className="mt-2 text-sm text-neutral-300">
              of at-risk clients are saved when intervention happens within 7 days of the health
              drop. Your system uses this data to time interventions correctly.
            </p>
          </div>
          <p className="leading-relaxed text-neutral-300">
            We know the average health score when clients churn. We know which communication
            channels get the best response rates. We know the optimal check-in frequency by agency
            type. We know that single-threaded client relationships churn at 3x the rate of
            multi-threaded ones.
          </p>
          <p className="mt-5 leading-relaxed text-neutral-300">
            No individual agency has enough data to know any of this. Your system does — because
            it&apos;s connected to the network.
          </p>
        </div>
      </section>

      <section className="bg-white px-6 py-16 text-neutral-900 md:py-20">
        <div className="mx-auto max-w-4xl">
          <h2 className="text-center text-3xl font-semibold tracking-tight md:text-4xl">FAQ</h2>
          <div className="mt-10 space-y-3">
            {faqs.map((faq, index) => {
              const isOpen = activeFaqIndex === index;
              return (
                <article key={faq.question} className="overflow-hidden rounded-xl border border-neutral-200">
                  <button
                    className="flex w-full items-center justify-between gap-4 bg-white px-5 py-4 text-left"
                    onClick={() => setActiveFaqIndex(isOpen ? null : index)}
                  >
                    <p className="font-semibold text-neutral-900">{faq.question}</p>
                    <span className="text-xl text-neutral-500">{isOpen ? '−' : '+'}</span>
                  </button>
                  {isOpen ? (
                    <p className="px-5 pb-5 text-sm leading-relaxed text-neutral-700">{faq.answer}</p>
                  ) : null}
                </article>
              );
            })}
          </div>
        </div>
      </section>

      <section id="booking" className="bg-black px-6 py-16 md:py-20">
        <div className="mx-auto max-w-5xl text-center">
          <h2 className="text-4xl font-semibold tracking-tight md:text-5xl">Book your deployment call.</h2>
          <p className="mx-auto mt-5 max-w-3xl text-neutral-300">
            30 minutes. I&apos;ll map your current operations, show you exactly where the gaps are, and
            walk through what the system looks like configured for your agency. If it&apos;s a fit, we
            start deployment the following week.
          </p>
          <div className="mt-8">
            <a
              href="#booking-widget"
              onClick={handleCtaClick}
              className="inline-flex items-center justify-center rounded-full bg-[#5500FF] px-9 py-3 text-sm font-semibold text-white transition hover:bg-[#6d23ff]"
            >
              Book the call
            </a>
          </div>
          <p className="mt-4 text-sm text-neutral-400">
            No pitch unless it&apos;s a fit. If it&apos;s not, you&apos;ll walk away with a clear picture of the
            operational gaps most agencies don&apos;t see.
          </p>

          <div id="booking-widget" className="mt-10 overflow-hidden rounded-2xl border border-white/10">
            <div className="h-[720px] w-full bg-neutral-950">
              <iframe
                title="Divine Acquisition Calendly Booking"
                src={CALENDLY_EMBED_URL}
                className="h-full w-full"
                loading="lazy"
              />
            </div>
          </div>
        </div>
      </section>

      <footer className="border-t border-white/10 bg-[#08080a] px-6 py-10 text-center">
        <p className="text-sm font-semibold">Divine Acquisition</p>
        <p className="mt-2 text-sm text-neutral-400">Devotion. Value. Exclusivity.</p>
        <p className="mt-2 text-sm text-neutral-500">divineacquisition.com</p>
      </footer>
    </main>
  );
}
